name: OWASP Security Check Pipeline

on:
  workflow_run:
    workflows:
      - Go Test Pipeline
    types:
      - completed
    status: success

jobs:
  depchecktest:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    name: Dependency Check for Go Project
    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2' # Replace with your Go version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run Dependency-Check
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'Go Dependency Check'
          path: '.'
          format: 'HTML'
          out: 'reports' # Default output directory
          args: >
            --failOnCVSS 7
            --enableRetired

      # Step 5: Upload Dependency-Check Report
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check Report
          path: ./reports/dependency-check-report.html
