name: Analyze Dependency-Check Report

on:
  workflow_run:
    workflows: OWASP Security Check Pipeline
    types:
      - completed

jobs:
  analyze-report:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the artifact from the first workflow
      - name: Download Dependency-Check Report
        uses: actions/download-artifact@v3
        with:
          name: Dependency-Check Report  # The artifact name must match the first workflow's artifact name
          path: ./downloaded-reports

      # Step 2: Print all vulnerabilities from the HTML report
      - name: Print all vulnerabilities from the report
        run: |
          echo "All vulnerabilities found:"
          cat ./downloaded-reports/dependency-check-report.html  # Print the entire HTML report
          
          # Alternatively, you can look for specific critical vulnerabilities
          if grep -qi 'Critical' ./downloaded-reports/dependency-check-report.html; then
            echo "Critical vulnerabilities found!"
            exit 1  # Fail the workflow if critical issues are found
          else
            echo "No critical vulnerabilities found."
          fi
