name: Secret Scan with TruffleHog

on:
  workflow_run:
    workflows:
      - OWASP Security Check Pipeline
    types:
      - completed
    status: success

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TruffleHog
        run: |
          python3 -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog scan
        run: |
          trufflehog --json  https://github.com/${{ github.repository }} > trufflehog-report.json

      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.json
