name: Build and Deploy Docker Image


on:
  workflow_run:
    workflows:
      - Secret Scan with TruffleHog
    types:
      - completed
    status: success

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello! This is a demo GitHub Actions workflow. 🚀"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2' # Replace with your Go version

      - name: Get commit hash
        id: get_commit
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Print commit hash for debugging
        run: |
          echo "Commit hash: ${{ env.COMMIT_HASH }}"


      - name: Build Go application
        run: |
          go build -ldflags "s -w -X main.Version=${{ env.COMMIT_HASH }}" -o app cmd/api/*


     

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
            # Build the Docker image and tag it with the GitHub SHA
            docker build -t demo-cloud-v2:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout Vulnerability Scan
        id: docker-scout
        uses: docker/scout-action@v1
        with:
                command: cves
                image: demo-cloud-v2:${{ github.sha }}  # Use the built image
                only-severities: critical,high
                write-comment: true
                github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            username: ${{ github.actor }}  # GitHub username
            password: ${{ secrets.GITHUB_TOKEN }}  # Your GitHub Personal Access Token

            # Tag and Push Docker Image
      - name: Tag and Push Docker image
        run: |
                docker tag demo-cloud-v2:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ github.sha }}
                docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
